version: '2'
services:
  ubuntu18:
    hostname: ubuntu_20
    container_name: ubuntu_20
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["/bin/bash"]
    volumes:
      - ./workspace:/workspace
    networks: 
      vpn:
        ipv4_address: 172.168.23.2
    restart: on-failure

  
networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.23.0/24
          gateway: 172.168.23.1
